FROM mcr.microsoft.com/devcontainers/base:1-bookworm

RUN apt-get update \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
      jq \
      ripgrep \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
