#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "Usage: npm run job:publish -- <job-name> <repo-name-or-owner/repo> [description]" >&2
  exit 64
}

if [[ $# -lt 2 ]]; then
  usage
fi

job_name="$1"
repo_name="$2"
description="${3:-Generated by Code Snuggie.}"
jobs_dir="${CODE_SNUGGIE_JOBS_DIR:-.code-snuggie/jobs}"
job_dir="$jobs_dir/$job_name"
workspace="$job_dir/workspace"

if [[ ! -d "$workspace" ]]; then
  echo "Missing workspace: $workspace" >&2
  exit 66
fi

if [[ -z "$(find "$workspace" -mindepth 1 -maxdepth 1 -print -quit)" ]]; then
  echo "Workspace is empty: $workspace" >&2
  exit 65
fi

if grep -R -I -E "(OPENAI_API_KEY|GITHUB_TOKEN|BEGIN [A-Z ]*PRIVATE KEY)" "$workspace" >/dev/null; then
  echo "Secret-like material found in workspace; refusing to publish." >&2
  exit 78
fi

(
  cd "$workspace"
  if [[ ! -d .git ]]; then
    git init
  fi

  git add .

  if git diff --cached --quiet; then
    echo "No staged changes to publish." >&2
  else
    git -c user.name="Code Snuggie" -c user.email="code-snuggie@example.invalid" commit -m "Create Codespaces-ready project"
  fi

  if ! gh repo view "$repo_name" >/dev/null 2>&1; then
    gh repo create "$repo_name" --private --description "$description" --source . --remote origin
  elif ! git remote get-url origin >/dev/null 2>&1; then
    origin_url="$(gh repo view "$repo_name" --json url --jq '.url')"
    git remote add origin "$origin_url"
  fi

  git push -u origin HEAD
)

{
  echo
  echo "## $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo
  echo "- Published workspace to private GitHub repo \`$repo_name\`."
} >> "$job_dir/LOG.md"
