#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "Usage: npm run job:publish -- <job-name> <repo-name-or-owner/repo> [description]" >&2
  exit 64
}

if [[ $# -lt 2 ]]; then
  usage
fi

job_name="$1"
repo_name="$2"
description="${3:-Generated by Code Snuggie.}"
jobs_dir="${CODE_SNUGGIE_JOBS_DIR:-.code-snuggie/jobs}"
job_dir="$jobs_dir/$job_name"
workspace="$job_dir/workspace"
publish_dir="$job_dir/publish"
branch_name="${CODE_SNUGGIE_PUBLISH_BRANCH:-code-snuggie/$job_name}"
base_branch="${CODE_SNUGGIE_PUBLISH_BASE:-main}"
pr_title="${CODE_SNUGGIE_PUBLISH_PR_TITLE:-Create Codespaces-ready project}"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$script_dir/.." && pwd)"

has_git_identity() {
  if git config --get user.name >/dev/null && git config --get user.email >/dev/null; then
    return 0
  fi

  [[ -n "${GIT_AUTHOR_NAME:-}" \
    && -n "${GIT_AUTHOR_EMAIL:-}" \
    && -n "${GIT_COMMITTER_NAME:-}" \
    && -n "${GIT_COMMITTER_EMAIL:-}" ]]
}

if [[ ! -d "$workspace" ]]; then
  echo "Missing workspace: $workspace" >&2
  exit 66
fi

if [[ -z "$(find "$workspace" -mindepth 1 -maxdepth 1 -print -quit)" ]]; then
  echo "Workspace is empty: $workspace" >&2
  exit 65
fi

workspace_abs="$(cd "$workspace" && pwd)"

if [[ "${CODE_SNUGGIE_ALLOW_UNRESTRICTED_EGRESS:-}" != "1" ]]; then
  if [[ ! -f "$workspace/.devcontainer/devcontainer.json" ]]; then
    echo "Missing .devcontainer/devcontainer.json; refusing to publish a Codespaces repo without devcontainer validation." >&2
    exit 78
  fi

  node "$root/scripts/check-devcontainer.mjs" \
    --require-restricted-egress \
    "$workspace/.devcontainer/devcontainer.json"
fi

(
  if ! has_git_identity; then
    echo "Git commit identity is not configured. Configure git or GIT_AUTHOR_*/GIT_COMMITTER_* before publishing; Code Snuggie will not modify git config." >&2
    exit 69
  fi

  if ! gh repo view "$repo_name" >/dev/null 2>&1; then
    gh repo create "$repo_name" --private --description "$description"
  fi

  repo_url="$(gh repo view "$repo_name" --json url --jq '.url')"
  repo_full_name="$(gh repo view "$repo_name" --json nameWithOwner --jq '.nameWithOwner')"
  default_branch="$(gh repo view "$repo_name" --json defaultBranchRef --jq '.defaultBranchRef.name // ""')"

  rm -rf "$publish_dir"

  if [[ -z "$default_branch" ]]; then
    mkdir -p "$publish_dir"
    cd "$publish_dir"
    git init -b "$base_branch"
    git remote add origin "$repo_url"

    if ! git rev-parse --verify "$base_branch" >/dev/null 2>&1; then
      git switch --orphan "$base_branch"
    else
      git switch "$base_branch"
    fi

    if ! git rev-parse --verify HEAD >/dev/null 2>&1; then
      git commit --allow-empty -m "Seed repository"
    fi

    git push "$repo_url" "HEAD:$base_branch"
    default_branch="$base_branch"
  else
    git clone "$repo_url" "$publish_dir"
    cd "$publish_dir"
    git fetch "$repo_url" "$default_branch"
    git switch -C "$branch_name" FETCH_HEAD
  fi

  if [[ "$(git branch --show-current)" != "$branch_name" ]]; then
    git switch -C "$branch_name" "$default_branch"
  fi

  rsync -a --delete \
    --exclude=".git/" \
    --exclude="node_modules/" \
    --exclude="build/" \
    --exclude="dist/" \
    --exclude="out/" \
    --exclude=".env" \
    --exclude=".env.*" \
    "$workspace_abs/" \
    ./

  if [[ -d ".devcontainer" ]]; then
    mapfile -d '' ignored_devcontainer_files < <(
      find .devcontainer -type f -print0 \
        | while IFS= read -r -d '' file; do
          if git check-ignore -q "$file"; then
            printf '%s\0' "$file"
          fi
        done
    )

    if ((${#ignored_devcontainer_files[@]} > 0)); then
      echo "Devcontainer support files are ignored by the destination .gitignore; refusing to publish missing PR files." >&2
      git check-ignore -v -- "${ignored_devcontainer_files[@]}" >&2 || true
      echo "Add a narrow .gitignore exception for each generated devcontainer support file that must be committed." >&2
      exit 78
    fi
  fi

  if [[ -f ".devcontainer/devcontainer.json" ]]; then
    destination_repo_permission="$(node --input-type=module - "$repo_full_name" <<'NODE'
import { readFileSync } from "node:fs";

const repo = process.argv[2];
const config = JSON.parse(readFileSync(".devcontainer/devcontainer.json", "utf8"));
const repositories = config.customizations?.codespaces?.repositories;

if (repositories && Object.hasOwn(repositories, repo)) {
  console.log(repo);
}
NODE
)"

    if [[ -n "$destination_repo_permission" ]]; then
      echo "Devcontainer requests Codespaces repository access for its own destination repo: $destination_repo_permission" >&2
      echo "Codespaces opened from that repo already receive the repo token; remove the redundant customizations.codespaces.repositories entry." >&2
      exit 78
    fi
  fi

  git add .

  mapfile -d '' publishable_files < <(git ls-files --cached --others --exclude-standard -z)
  if ((${#publishable_files[@]} > 0)) \
    && grep -I -E "(OPENAI_API_KEY|GITHUB_TOKEN|BEGIN [A-Z ]*PRIVATE KEY)" -- "${publishable_files[@]}" >/dev/null; then
    echo "Secret-like material found in publishable workspace files; refusing to publish." >&2
    exit 78
  fi

  if git diff --cached --quiet; then
    echo "No staged changes to publish." >&2
  else
    git commit -m "Create Codespaces-ready project"
  fi

  git push "$repo_url" "HEAD:$branch_name"

  pr_url="$(gh pr list --repo "$repo_name" --head "$branch_name" --state open --json url --jq '.[0].url // ""')"
  if [[ -z "$pr_url" ]]; then
    pr_url="$(gh pr create \
      --repo "$repo_name" \
      --base "$default_branch" \
      --head "$branch_name" \
      --title "$pr_title" \
      --body "$description")"
  fi

  echo "$pr_url" > "$job_dir/artifacts/pull-request-url.txt"
)

{
  echo
  echo "## $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo
  echo "- Published workspace to private GitHub repo \`$repo_name\` on branch \`$branch_name\`."
  echo "- Opened pull request: $(cat "$job_dir/artifacts/pull-request-url.txt")"
} >> "$job_dir/LOG.md"

cat "$job_dir/artifacts/pull-request-url.txt"
